/** Declaration file generated by dts-gen */

export class Parser {
    constructor(options: any);
    parseCode(buffer: any, filename: any): any;
    parseEval(buffer: any): any;
    tokenGetAll(buffer: any): any;
    static create(options: any): any;
    static parseCode(buffer: any, filename: any, options: any): any;
    static parseEval(buffer: any, options: any): any;
    static tokenGetAll(buffer: any, options: any): any;
}
